# Generated by Django 2.0 on 2018-02-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('madadju', '0001_initial'),
        ('karbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adapt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hamyar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_method', models.IntegerField(choices=[(0, 'text'), (1, 'email')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='karbar.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
                ('madadju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madadju.Madadju')),
            ],
        ),
        migrations.AddField(
            model_name='adapt',
            name='hamyar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamyar.Hamyar'),
        ),
        migrations.AddField(
            model_name='adapt',
            name='madadju',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madadju.Madadju'),
        ),
    ]
