# Generated by Django 2.0 on 2018-02-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamyar', '0002_auto_20180201_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFoundation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
